// Copyright (c) Damian Hickey. All rights reserved.
// See LICENSE in the project root for license information.

using System.Text.Json.Serialization;

namespace DamianH.NotionClient.Models.Blocks;

/// <summary>Programming / markup language for a code block.</summary>
public enum CodeLanguage
{
    [JsonPropertyName("abap")] Abap,
    [JsonPropertyName("abc")] Abc,
    [JsonPropertyName("agda")] Agda,
    [JsonPropertyName("arduino")] Arduino,
    [JsonPropertyName("ascii art")] AsciiArt,
    [JsonPropertyName("assembly")] Assembly,
    [JsonPropertyName("bash")] Bash,
    [JsonPropertyName("basic")] Basic,
    [JsonPropertyName("bnf")] Bnf,
    [JsonPropertyName("c")] C,
    [JsonPropertyName("c#")] CSharp,
    [JsonPropertyName("c++")] CPlusPlus,
    [JsonPropertyName("clojure")] Clojure,
    [JsonPropertyName("coffeescript")] Coffeescript,
    [JsonPropertyName("coq")] Coq,
    [JsonPropertyName("css")] Css,
    [JsonPropertyName("dart")] Dart,
    [JsonPropertyName("dhall")] Dhall,
    [JsonPropertyName("diff")] Diff,
    [JsonPropertyName("docker")] Docker,
    [JsonPropertyName("ebnf")] Ebnf,
    [JsonPropertyName("elixir")] Elixir,
    [JsonPropertyName("elm")] Elm,
    [JsonPropertyName("erlang")] Erlang,
    [JsonPropertyName("f#")] FSharp,
    [JsonPropertyName("flow")] Flow,
    [JsonPropertyName("fortran")] Fortran,
    [JsonPropertyName("gherkin")] Gherkin,
    [JsonPropertyName("glsl")] Glsl,
    [JsonPropertyName("go")] Go,
    [JsonPropertyName("graphql")] GraphQL,
    [JsonPropertyName("groovy")] Groovy,
    [JsonPropertyName("haskell")] Haskell,
    [JsonPropertyName("hcl")] Hcl,
    [JsonPropertyName("html")] Html,
    [JsonPropertyName("idris")] Idris,
    [JsonPropertyName("java")] Java,
    [JsonPropertyName("javascript")] JavaScript,
    [JsonPropertyName("json")] Json,
    [JsonPropertyName("julia")] Julia,
    [JsonPropertyName("kotlin")] Kotlin,
    [JsonPropertyName("latex")] Latex,
    [JsonPropertyName("less")] Less,
    [JsonPropertyName("lisp")] Lisp,
    [JsonPropertyName("livescript")] Livescript,
    [JsonPropertyName("llvm ir")] LlvmIr,
    [JsonPropertyName("lua")] Lua,
    [JsonPropertyName("makefile")] Makefile,
    [JsonPropertyName("markdown")] Markdown,
    [JsonPropertyName("markup")] Markup,
    [JsonPropertyName("matlab")] Matlab,
    [JsonPropertyName("mathematica")] Mathematica,
    [JsonPropertyName("mermaid")] Mermaid,
    [JsonPropertyName("nix")] Nix,
    [JsonPropertyName("notion formula")] NotionFormula,
    [JsonPropertyName("objective-c")] ObjectiveC,
    [JsonPropertyName("ocaml")] Ocaml,
    [JsonPropertyName("pascal")] Pascal,
    [JsonPropertyName("perl")] Perl,
    [JsonPropertyName("php")] Php,
    [JsonPropertyName("plain text")] PlainText,
    [JsonPropertyName("powershell")] PowerShell,
    [JsonPropertyName("prolog")] Prolog,
    [JsonPropertyName("protobuf")] Protobuf,
    [JsonPropertyName("purescript")] Purescript,
    [JsonPropertyName("python")] Python,
    [JsonPropertyName("r")] R,
    [JsonPropertyName("racket")] Racket,
    [JsonPropertyName("reason")] Reason,
    [JsonPropertyName("ruby")] Ruby,
    [JsonPropertyName("rust")] Rust,
    [JsonPropertyName("sass")] Sass,
    [JsonPropertyName("scala")] Scala,
    [JsonPropertyName("scheme")] Scheme,
    [JsonPropertyName("scss")] Scss,
    [JsonPropertyName("shell")] Shell,
    [JsonPropertyName("smalltalk")] Smalltalk,
    [JsonPropertyName("solidity")] Solidity,
    [JsonPropertyName("sql")] Sql,
    [JsonPropertyName("swift")] Swift,
    [JsonPropertyName("toml")] Toml,
    [JsonPropertyName("typescript")] TypeScript,
    [JsonPropertyName("vb.net")] VbNet,
    [JsonPropertyName("verilog")] Verilog,
    [JsonPropertyName("vhdl")] Vhdl,
    [JsonPropertyName("visual basic")] VisualBasic,
    [JsonPropertyName("webassembly")] WebAssembly,
    [JsonPropertyName("xml")] Xml,
    [JsonPropertyName("yaml")] Yaml,
    [JsonPropertyName("java/c/c++/c#")] JavaCCPlusPlusCSharp,
}
